name: Deploy Frontend to BigRock

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build frontend
      - name: Build frontend
        run: npm run build

      # Step 5: Deploy to BigRock via FTP
      - name: Deploy to BigRock
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.BIGROCK_HOST }}      # FTP host
          username: ${{ secrets.BIGROCK_USER }}    # FTP username
          password: ${{ secrets.BIGROCK_PASSWORD }}# FTP password
          local-dir: dist                           # Vite build output
          server-dir: /public_html                  # Deployment folder
          git-ftp-args: --insecure                 # Optional: bypass SSL if needed